# Generated by Django 3.2.5 on 2021-07-27 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='currently_reading',
        ),
    ]
