# Generated by Django 3.2.5 on 2021-08-02 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20210726_0805'),
        ('authors', '0002_alter_author_middle_name'),
        ('users', '0004_remove_user_currently_reading'),
        ('images', '0003_auto_20210726_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='authors.author'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='books.book'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='users.user'),
        ),
    ]
